Repository jina-ai/dashboard, pull requests merged in 2021-06, with the labels that each got.

#338 fix(snackbar): fix the snackbar close operation once it is opened
  src/components/Hub/CodeSnippetWithCopy.tsx
Labels: size/XS

#323 Feat 296 enhance hub landing page UI
  cypress.json
  cypress/integration/views/flowview.ts
  cypress/integration/views/hubView.ts
  cypress/integration/views/podView.ts
  cypress/integration/visual-tests/flowDesign.ts
  src/assets/icons/hub-icon.svg
  src/components/Hub/FilterButton.tsx
  src/components/Hub/HubFilters.test.tsx
  src/components/Hub/HubImagesList.tsx
  src/components/Hub/HubImagesListPreview.tsx
  src/components/Hub/HubOverviewAction.tsx
  src/components/Hub/HubOverviewActionsContainer.tsx
  src/components/Hub/HubRecommendedCategories.tsx
  src/components/Hub/ImageCard.tsx
  src/components/Hub/__snapshots__/HubImagesListPreview.test.tsx.snap
  src/components/Hub/__snapshots__/HubOverviewActionsContainer.test.tsx.snap
  src/components/Hub/__snapshots__/ImageCard.test.tsx.snap
  src/components/Layout/MainNavbar/MainNavbar.tsx
  src/components/Styleguide/__snapshots__/ColorsPage.test.tsx.snap
  src/helpers/tests/utils.test.ts
  src/redux/hub/hub.actions.ts
  src/redux/hub/hub.constants.ts
  src/redux/hub/hub.reducer.ts
  src/redux/hub/hub.test.ts
  src/redux/hub/hub.types.ts
  src/theme.ts
  src/views/HubView.tsx
Labels: size/XL

#334 Debugging tool
  .env
  .env.production
  src/components/DebuggingTool/FlowChartNodes.tsx
  src/components/DebuggingTool/Matches.tsx
  src/components/DebuggingTool/Response.tsx
  src/components/DebuggingTool/RouteTable.tsx
  src/components/DebuggingTool/Scores.tsx
  src/components/DebuggingTool/tests/Matches.test.tsx
  src/components/DebuggingTool/tests/Matches.testData.ts
  src/redux/global/global.constants.ts
  src/redux/global/global.selectors.ts
  src/redux/global/global.test.ts
  src/redux/global/global.types.ts
  src/routes/Dashboard.tsx
  src/views/DebuggingTool.tsx
Labels: size/XL

#333 Style hub list restyle 314
  cypress/integration/views/hubView.ts
  cypress/integration/views/logsView.ts
  src/assets/icons/Copy.svg
  src/components/Common/ExpandingSearchbar.test.tsx
  src/components/Common/ExpandingSearchbar.tsx
  src/components/Hub/CodeSnippetWithCopy.tsx
  src/components/Hub/FilterButton.tsx
  src/components/Hub/HubFilters.tsx
  src/components/Hub/HubImagesList.tsx
  src/components/Hub/HubOverviewActionsContainer.tsx
  src/components/Hub/HubSortDropdown.tsx
  src/components/Hub/ImageCard.tsx
  src/components/Hub/__snapshots__/HubOverviewActionsContainer.test.tsx.snap
  src/components/Hub/__snapshots__/ImageCard.test.tsx.snap
  src/components/Hub/__snapshots__/ImageDetails.test.tsx.snap
  src/components/Styleguide/__snapshots__/ColorsPage.test.tsx.snap
  src/helpers/format.ts
  src/helpers/hubHelpers.ts
  src/helpers/tests/hubHelpers.test.ts
  src/redux/hub/hub.constants.ts
  src/redux/hub/hub.types.ts
  src/theme.ts
Labels: size/L

#339 feat: multimedia request/response
  package-lock.json
  src/App.css
  src/components/DebuggingTool/FlowChartNodes.tsx
  src/components/DebuggingTool/Matches.tsx
  src/components/DebuggingTool/Request.tsx
  src/components/DebuggingTool/Response.tsx
  src/components/DebuggingTool/RouteTable.tsx
  src/components/DebuggingTool/Scores.tsx
  src/components/DebuggingTool/tests/Matches.test.tsx
  src/components/DebuggingTool/tests/Matches.testData.ts
  src/helpers/format.ts
  src/helpers/tests/format.test.ts
  src/views/DebuggingTool.tsx
Labels: size/XL

#346 feat: swagger view
  package-lock.json
  package.json
  src/apps/Swagger.tsx
  src/components/DebuggingTool/CustomLiveResponse.tsx
  src/index.tsx
  src/layouts/SwaggerLayout.tsx
  src/layouts/index.ts
  src/routes/Dashboard.tsx
  src/routes/Swagger.tsx
  src/routes/index.ts
  src/views/SwaggerView.tsx
Labels: size/XL
