Repository jina-ai/dashboard, pull requests merged in 2021-02, with the labels that each got.

#149 fix: change start script to run dashboard on windows
  package.json
  src/index.tsx
Labels: size/S

#143 Feat/jinahub 30 hub images filter sort
  .env
  .gitignore
  cypress/fixtures/example.json
  cypress/fixtures/hubImages.json
  cypress/integration/views/hubView.ts
  package-lock.json
  package.json
  src/components/Hub/HubFilters.test.tsx
  src/components/Hub/HubFilters.tsx
  src/components/Hub/HubImageLIst.test.tsx
  src/components/Hub/HubImagesList.tsx
  src/components/Hub/HubImagesListPreview.tsx
  src/components/Hub/ImageCard.tsx
  src/components/Hub/__snapshots__/HubImagesListPreview.test.tsx.snap
  src/flux/api.ts
  src/flux/store.ts
  src/redux/global/global.actions.ts
  src/redux/hub/hub.actions.ts
  src/redux/hub/hub.constants.ts
  src/redux/hub/hub.reducer.ts
  src/redux/hub/hub.selectors.ts
  src/redux/hub/hub.test.ts
  src/redux/hub/hub.types.ts
  src/redux/index.ts
  src/services/hubApi.test.ts
  src/services/hubApi.ts
  src/types.d.ts
  src/views/HubView.tsx
Labels: size/XL

#148 Implement flow canvas design
  cypress/integration/views/flowview.js
  cypress/integration/views/flowview.ts
  src/App.css
  src/assets/icons/Play.svg
  src/assets/icons/Save.svg
  src/assets/icons/Stop.svg
  src/assets/icons/Upload.svg
  src/assets/icons/Yaml.svg
  src/components/FlowChart/ChartNode.tsx
  src/components/FlowChart/CommandBar.tsx
  src/components/FlowChart/FlowSelection.tsx
  src/components/FlowChart/NodePort.tsx
  src/components/FlowChart/Sidebar.tsx
  src/data/defaultPods.json
  src/data/defaultPods.ts
  src/data/tooltipConfig.ts
  src/emotion.d.ts
  src/helpers/flow-chart.ts
  src/layouts/IconSidebar.tsx
  src/modals/NewFlow.tsx
  src/modals/PodEdit.tsx
  src/redux/flows/flows.actions.ts
  src/redux/flows/flows.constants.ts
  src/redux/flows/flows.reducer.ts
  src/redux/flows/flows.selectors.ts
  src/redux/flows/flows.test.ts
  src/redux/flows/flows.testData.ts
  src/redux/flows/flows.types.ts
  src/redux/global/global.actions.ts
  src/redux/global/global.constants.ts
  src/redux/global/global.reducer.ts
  src/redux/global/global.test.ts
  src/redux/global/global.testData.ts
  src/redux/global/global.types.ts
  src/styles/_icons.scss
  src/styles/fonts/Montserrat/Montserrat-Regular.ttf
  src/theme.ts
  src/views/FlowView.tsx
Labels: size/XL

#153 Fix clearline to work in ci
  dev-resources/testServer.js
Labels: size/S

#154 Fix flowView integration tests
  cypress/integration/views/flowview.ts
  src/components/Common/ConnectionBanner.tsx
  src/components/Common/ConnectionToast.tsx
  src/components/Common/InfoToast.tsx
  src/components/FlowChart/Sidebar.tsx
  src/components/FlowChart/SidebarItem.tsx
  src/redux/settings/settings.constants.ts
Labels: size/S

#157 Flow: Fixes
  src/components/FlowChart/CommandBar.tsx
Labels: size/XS

#158 Fix: Remove LogIn from Hub
  src/components/Layout/MainNavbar/MainNavbar.tsx
Labels: size/S

#155 Fix: Hide taskView
  src/redux/global/global.constants.ts
Labels: size/XS

#156 Chore/add workflow to sync version to jina version
  .github/workflows/deploy.yml
  .github/workflows/sync-version-with-jina.yml
Labels: size/S

#159 ci: fix version substitution
  .github/workflows/sync-version-with-jina.yml
Labels: size/XS

#161 ci: allow same version
  .github/workflows/sync-version-with-jina.yml
Labels: size/XS

#152 fix: YAML flow parser
  src/helpers/flow-chart.ts
  src/helpers/tests/flow-chart.test.ts
  src/helpers/tests/flow-chart.testData.ts
  src/helpers/tests/format.test.ts
  src/helpers/tests/format.testData.ts
  src/layouts/IconSidebar.tsx
  src/redux/flows/flows.actions.ts
  src/redux/flows/flows.constants.ts
  src/redux/flows/flows.reducer.ts
  src/redux/flows/flows.test.ts
  src/redux/flows/flows.types.ts
Labels: size/M

#167 Fix command buttons
  src/assets/icons/Yaml.svg
  src/components/FlowChart/CommandBar.tsx
Labels: size/S

#168 Fix: Add link deletion to reducer
  src/redux/flows/flows.reducer.ts
  src/redux/flows/flows.test.ts
  src/redux/flows/flows.testData.ts
  src/redux/flows/flows.types.ts
Labels: size/S

#171 ci: remove manual tagging
  .github/workflows/sync-version-with-jina.yml
Labels: size/XS

#165 Fix: Add error handling to parseYAML
  src/flux/store.ts
  src/helpers/format.ts
  src/redux/flows/flows.reducer.ts
Labels: size/S

#169 Refactor: Delete store and unused code
  src/apps/Dashboard.tsx
  src/apps/Hub.tsx
  src/components/Layout/MainNavbar/MainNavbar.tsx
  src/flux/api.ts
  src/flux/config.ts
  src/flux/constants.ts
  src/flux/dispatcher.ts
  src/flux/hub.ts
  src/flux/index.ts
  src/flux/jinad.ts
  src/flux/store.ts
  src/flux/tranformLog.ts
  src/layouts/HubLayout.tsx
  src/layouts/IconSidebar.tsx
  src/views/LogIn.tsx
  src/views/PackageView.tsx
Labels: size/XL

#162 feat: hub pod overview
  cypress/integration/views/hubView.ts
  src/components/Common/NavigateButton.tsx
  src/components/Common/SpinningLoader.tsx
  src/components/Hub/CopyCommand.tsx
  src/components/Hub/HubFilters.tsx
  src/components/Hub/HubImageLIst.test.tsx
  src/components/Hub/HubImagesList.tsx
  src/components/Hub/HubImagesListPreview.test.tsx
  src/components/Hub/HubImagesListPreview.tsx
  src/components/Hub/ImageCard.tsx
  src/components/Hub/ImageDetails.tsx
  src/components/Hub/ImageReviews.tsx
  src/components/Hub/Readme.tsx
  src/components/Hub/__snapshots__/HubImagesListPreview.test.tsx.snap
  src/components/Hub/types.ts
  src/components/Layout/MainNavbar/MainNavbar.tsx
  src/components/Task/BarChartCard.tsx
  src/emotion.d.ts
  src/layouts/IconSidebar.tsx
  src/redux/hub/hub.actions.ts
  src/redux/hub/hub.reducer.ts
  src/redux/hub/hub.selectors.ts
  src/redux/hub/hub.test.ts
  src/redux/hub/hub.types.ts
  src/routes/Dashboard.tsx
  src/services/hubApi.test.ts
  src/services/hubApi.ts
  src/theme.ts
  src/views/HubView.tsx
  src/views/PackageView.tsx
Labels: size/XL

#173 Fix/jina hub standalone routes
  src/layouts/HubLayout.tsx
  src/routes/Hub.tsx
Labels: size/S

#176 chore: update lint config
  .prettierrc
  src/components/Hub/BuildHistory.tsx
  src/components/Hub/CopyCommand.tsx
Labels: size/S

#170 Test: Add test for logs in LogView
  cypress/fixtures/sample-output.json
  cypress/integration/views/logsView.ts
  dev-resources/config.js
  src/components/FlowChart/CommandBar.tsx
  src/components/LogStream/LogItem.tsx
  src/redux/logStream/logStream.actions.ts
Labels: size/S

#174 test: create snapshot test for flow design
  cypress/integration/visual-tests/flowDesign.ts
Labels: size/S

#177 ci: add netlify.toml with build ignore
  netlify.toml
Labels: size/XS

#185 Feat: immerJS for global-133
  src/redux/global/global.reducer.ts
Labels: size/M

#190 feat: add sentry to track performance and errors
  package-lock.json
  package.json
  src/index.tsx
Labels: size/M

#175 feat: add styleguide
  package.json
  src/apps/Styleguide.tsx
  src/components/Common/Typography.tsx
  src/components/Layout/MainSidebar/MainSidebar.tsx
  src/components/Styleguide/ColorsPage.test.tsx
  src/components/Styleguide/ColorsPage.tsx
  src/components/Styleguide/MiscPage.test.tsx
  src/components/Styleguide/MiscPage.tsx
  src/components/Styleguide/TypographyPage.test.tsx
  src/components/Styleguide/TypographyPage.tsx
  src/components/Styleguide/__snapshots__/ColorsPage.test.tsx.snap
  src/components/Styleguide/__snapshots__/MiscPage.test.tsx.snap
  src/components/Styleguide/__snapshots__/TypographyPage.test.tsx.snap
  src/index.tsx
  src/redux/global/global.types.ts
  src/routes/Styleguide.tsx
  src/styles/mediaQuery.test.ts
  src/styles/mediaQuery.ts
  src/views/PackageView.tsx
Labels: size/L

#183 Fix: pod font size
  src/App.css
Labels: size/XS

#195 feat: connection auto-refresh
  src/components/Styleguide/__snapshots__/TypographyPage.test.tsx.snap
  src/helpers/tests/utils.test.ts
  src/helpers/utils.ts
  src/redux/flows/flows.actions.ts
  src/redux/logStream/logStream.actions.ts
  src/services/config.ts
  src/services/jinad.ts
  src/services/tests/jinad.test.ts
  src/services/tests/jinad.testData.ts
Labels: size/L
