Repository jina-ai/dashboard, pull requests merged in 2021-01, with the labels that each got.

#123 Remove actions/labler
  .github/workflows/label-pr.yml
Labels: size/XS

#120 Feat: redux log stream integration
  cypress/integration/views/flowview.js
  src/components/LogStream/LogLevelPieChart.tsx
  src/components/LogStream/LogsTable.tsx
  src/components/LogStream/PieChartBase.tsx
  src/flux/api.ts
  src/flux/store.ts
  src/helpers/format.ts
  src/helpers/tests/format.test.ts
  src/helpers/tests/format.testData.ts
  src/redux/index.ts
  src/redux/logStream/logStream.actions.ts
  src/redux/logStream/logStream.constants.ts
  src/redux/logStream/logStream.reducer.ts
  src/redux/logStream/logStream.selectors.ts
  src/redux/logStream/logStream.test.ts
  src/redux/logStream/logStream.testData.ts
  src/redux/logStream/logStream.types.ts
  src/views/LogsView.tsx
Labels: size/XL

#129 fix: use readline module to clear dev-server logs before writing
  .github/workflows/ci.yml
  dev-resources/testServer.js
Labels: size/S

#130 fix: address lint warnings
  src/components/Common/MultiFilterSelect.tsx
  src/components/Layout/MainSidebar/SidebarMainNavbar.tsx
  src/components/Layout/MainSidebar/SidebarNavItem.tsx
  src/components/Layout/MainSidebar/SidebarNavItems.tsx
  src/data/exampleFlows.ts
  src/data/sidebar-nav-items.ts
  src/flux/api.ts
  src/modals/LogDetails.tsx
  src/modals/PasteYAML.tsx
Labels: size/S

#131 Refactor: Hublayout and IconSideBar to funcComponents
  src/layouts/HubLayout.tsx
  src/layouts/IconSidebar.tsx
Labels: size/M

#132 Feat redux global integration
  package-lock.json
  package.json
  src/components/Common/InfoToast.tsx
  src/components/Layout/MainSidebar/SidebarNavItem.tsx
  src/components/Layout/MainSidebar/SidebarNavItems.tsx
  src/data/podProperties.json
  src/flux/store.ts
  src/helpers/format.ts
  src/layouts/HubLayout.tsx
  src/layouts/IconSidebar.tsx
  src/modals/LogDetails.tsx
  src/redux/global/global.actions.ts
  src/redux/global/global.constants.ts
  src/redux/global/global.reducer.ts
  src/redux/global/global.selectors.ts
  src/redux/global/global.test.ts
  src/redux/global/global.testData.ts
  src/redux/global/global.types.ts
  src/redux/index.ts
  src/redux/logStream/logStream.constants.ts
  src/redux/logStream/logStream.reducer.ts
  src/redux/logStream/logStream.types.ts
  src/views/FlowView.tsx
  src/views/LogsView.tsx
Labels: size/XL

#134 Feat: redux task integration
  package-lock.json
  package.json
  src/flux/api.ts
  src/redux/global/global.types.ts
  src/redux/index.ts
  src/redux/task/task.actions.ts
  src/redux/task/task.constants.ts
  src/redux/task/task.reducer.ts
  src/redux/task/task.selectors.ts
  src/redux/task/task.test.ts
  src/redux/task/task.testData.ts
  src/redux/task/task.types.ts
  src/views/TaskView.tsx
Labels: size/L

#135 test: add percy for visual testing
  .github/workflows/ci.yml
  cypress/integration/visual-tests/helpPage.ts
  cypress/plugins/index.js
  cypress/support/commands.ts
  cypress/tsconfig.json
  package-lock.json
  package.json
  src/views/NotFound.tsx
Labels: size/XL

#128 feat: add overview actions in Hub view
  cypress/integration/views/hubView.ts
  package-lock.json
  package.json
  src/App.css
  src/components/Hub/HubImagesList.tsx
  src/components/Hub/HubImagesListPreview.test.tsx
  src/components/Hub/HubImagesListPreview.tsx
  src/components/Hub/HubOverviewAction.tsx
  src/components/Hub/HubOverviewActionsContainer.test.tsx
  src/components/Hub/HubOverviewActionsContainer.tsx
  src/components/Hub/ImageCard.tsx
  src/components/Hub/ImageReviews.tsx
  src/components/Hub/ReviewCard.tsx
  src/components/Hub/StarRating.test.ts
  src/components/Hub/StarRating.tsx
  src/components/Hub/__snapshots__/HubImagesListPreview.test.tsx.snap
  src/components/Hub/__snapshots__/HubOverviewActionsContainer.test.tsx.snap
  src/components/LogStream/LogItem.tsx
  src/components/LogStream/LogsTableHeader.tsx
  src/views/HubView.tsx
  src/views/PackageView.tsx
Labels: size/XL

#136 test: add integration test for help view
  cypress/integration/views/helpView.ts
  src/components/Common/HelpCard.tsx
  src/views/NotFound.tsx
Labels: size/S

#139 fix: add dependency @dabh/diagnostics that was accidently removed
  package-lock.json
Labels: size/S

#146 docs: remove deprecated content
  README.md
Labels: size/M

#144 Fix: Import Yaml Bug
  src/components/FlowChart/CommandBar.tsx
  src/layouts/IconSidebar.tsx
Labels: size/S
