Repository jina-ai/dashboard, pull requests merged in 2021-09, with the labels that each got.

#301 Feat: file handling
  .stylelintrc.json
  src/App.css
  src/components/Common/Button.tsx
  src/components/Common/Card.tsx
  src/components/Common/ConnectionToast.tsx
  src/components/Common/CookiesBanner.tsx
  src/components/Common/InfoToast.tsx
  src/components/Common/PageTitle.tsx
  src/components/FlowChart/FlowSelection.tsx
  src/components/FlowChart/WorkspaceSelection.tsx
  src/components/Layout/MainFooter.tsx
  src/components/Layout/SideNavBar/NavLogo.tsx
  src/components/Layout/SideNavBar/SidebarNavItem.tsx
  src/components/Layout/TopNavBar/TopNavBar.tsx
  src/components/Layout/TopNavBar/UserActions.tsx
  src/components/LogStream/LogLevelPieChart.tsx
  src/components/LogStream/LogLevelSummaryChart.tsx
  src/components/Settings/Settings.tsx
  src/components/Task/ElapsedCard.tsx
  src/helpers/tests/utils.test.ts
  src/index.css
  src/layouts/HubLayout.tsx
  src/modals/ConfigFileUpload.tsx
  src/modals/LogDetails.tsx
  src/modals/MultiModalExample.tsx
  src/redux/flows/flows.actions.test.ts
  src/redux/flows/flows.actions.ts
  src/redux/flows/flows.constants.ts
  src/redux/flows/flows.reducer.ts
  src/redux/flows/flows.selectors.ts
  src/redux/flows/flows.test.ts
  src/redux/flows/flows.testData.ts
  src/redux/global/global.types.ts
  src/redux/hub/hub.test.ts
  src/redux/index.ts
  src/redux/logStream/logStream.actions.ts
  src/services/jinad.ts
  src/services/tests/gatewayClient.ts
  src/types.d.ts
  src/views/FlowView.tsx
  src/views/LogIn.tsx
  src/views/Settings.tsx
  src/views/TaskView.tsx
Labels: size/XL

#366 style(settings): add styles in settings menu form
  src/components/Settings/FormItem.tsx
  src/components/Settings/Settings.tsx
  src/components/Settings/ToggleButton.tsx
  tailwind.config.js
Labels: size/M

#368 fix(LogsTableHeader): fix header style of LogsTableHeader
  src/components/LogStream/LogsTableHeader.tsx
  tailwind.config.js
Labels: size/S
