Repository jina-ai/dashboard, pull requests merged in 2021-03, with the labels that each got.

#178 improve tests for hub selectors and components
  src/components/Hub/ImageCard.test.tsx
  src/components/Hub/ImageDetails.test.tsx
  src/components/Hub/Readme.test.tsx
  src/components/Hub/__snapshots__/ImageCard.test.tsx.snap
  src/components/Hub/__snapshots__/ImageDetails.test.tsx.snap
  src/components/Hub/__snapshots__/Readme.test.tsx.snap
  src/redux/hub/hub.test.ts
  src/services/hubApi.test.ts
  src/services/hubApi.ts
  src/services/tests/hubApi.test.ts
Labels: size/M

#231 style(hub): change to color from theme
  src/components/Hub/HubOverviewAction.tsx
Labels: size/S

#199 Feat react flow renderer
  cypress/integration/views/logsView.ts
  cypress/integration/visual-tests/flowDesign.ts
  package-lock.json
  package.json
  src/App.css
  src/components/FlowChart/ChartNode.tsx
  src/components/FlowChart/FlowChart.tsx
  src/components/FlowChart/FlowSelection.tsx
  src/components/FlowChart/NodePort.tsx
  src/components/FlowChart/Sidebar.tsx
  src/components/FlowChart/SidebarItem.tsx
  src/helpers/flow-chart.ts
  src/helpers/format.ts
  src/helpers/tests/flow-chart.test.ts
  src/helpers/tests/flow-chart.testData.ts
  src/helpers/tests/format.testData.ts
  src/helpers/typeCheckers.ts
  src/modals/PodEdit.tsx
  src/redux/flows/flows.actions.ts
  src/redux/flows/flows.constants.ts
  src/redux/flows/flows.reducer.ts
  src/redux/flows/flows.selectors.ts
  src/redux/flows/flows.test.ts
  src/redux/flows/flows.testData.ts
  src/redux/flows/flows.types.ts
  src/redux/global/global.actions.ts
  src/routes/Dashboard.tsx
  src/views/FlowView.tsx
Labels: size/XL

#234 Fix: localStorage flowChart bug
  src/views/FallbackPage.tsx
Labels: size/S

#225 New pr tags
  .github/workflows/label-pr.yml
Labels: size/XS

#239 test: ignore directories like components and styles in code coverage
  codecov.yml
Labels: size/XS

#237 Fix flow deletion 236
  cypress/integration/views/flowview.ts
  src/components/FlowChart/FlowSelection.tsx
  src/components/Hub/__snapshots__/HubOverviewActionsContainer.test.tsx.snap
  src/modals/NewFlow.tsx
Labels: size/S

#242 Enhancement/209 command bar theme palette
  src/components/FlowChart/CommandBar.tsx
Labels: size/S

#232 Typing and todos 201
  src/apps/Dashboard.tsx
  src/apps/Hub.tsx
  src/components/Common/MultiFilterSelect.tsx
  src/components/FlowChart/ChartNode.tsx
  src/components/FlowChart/FlowChart.tsx
  src/components/FlowChart/FlowSelection.tsx
  src/components/FlowChart/Sidebar.tsx
  src/components/FlowChart/SidebarItem.tsx
  src/components/Layout/MainNavbar/MainNavbar.tsx
  src/components/Layout/MainNavbar/UserActions.tsx
  src/components/LogStream/BarChartBase.tsx
  src/components/LogStream/LogGroup.tsx
  src/components/LogStream/LogItem.tsx
  src/components/LogStream/LogLevelSummaryChart.tsx
  src/components/LogStream/LogsTable.tsx
  src/components/LogStream/PieChartBase.tsx
  src/components/LogStream/levels.ts
  src/components/LogStream/types.ts
  src/components/Settings/FormItem.tsx
  src/components/Task/BarChartCard.tsx
  src/components/Task/ProgressCard.tsx
  src/components/Task/QueriesPerSecond.tsx
  src/components/Task/SpeedCard.tsx
  src/data/exampleFlows.ts
  src/data/globalArguments.ts
  src/helpers/flow-chart.ts
  src/helpers/format.ts
  src/hooks/useDebounce.ts
  src/hooks/useEffectOnce.ts
  src/hooks/useThrottleFn.ts
  src/hooks/useTimeoutFn.ts
  src/hooks/useUnmount.ts
  src/layouts/HubLayout.tsx
  src/logger.ts
  src/modals/FlowSettings.tsx
  src/modals/LogDetails.tsx
  src/modals/PasteYAML.tsx
  src/modals/PodEdit.tsx
  src/modals/WriteReview.tsx
  src/redux/flows/flows.actions.ts
  src/redux/flows/flows.constants.ts
  src/redux/flows/flows.reducer.ts
  src/redux/flows/flows.selectors.ts
  src/redux/flows/flows.test.ts
  src/redux/flows/flows.testData.ts
  src/redux/flows/flows.types.ts
  src/redux/global/global.types.ts
  src/redux/logStream/logStream.types.ts
  src/redux/settings/settings.test.ts
  src/redux/task/task.reducer.ts
  src/routes/Hub.tsx
  src/services/hubApi.ts
  src/views/FlowView.tsx
  src/views/LogsView.tsx
  src/withTracker.tsx
Labels: size/XL

#241 test: use cypress coverage to get coverage of integration tests
  .github/workflows/ci.yml
  cypress/plugins/index.js
  cypress/support/index.ts
  package-lock.json
  package.json
Labels: size/XL

#240 Fix: delete custom flow 221
  src/components/FlowChart/FlowSelection.tsx
Labels: size/S

#255 feat: version control
  src/index.tsx
  src/views/FallbackPage.tsx
Labels: size/S

#248 test: improve tests for hub api
  src/services/tests/hubApi.test.ts
Labels: size/S

#260 docs: update usage in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: size/XS

#259 Refactor code type
  src/apps/Dashboard.tsx
  src/components/Common/MultiFilterSelect.tsx
  src/components/LogStream/LogsTable.tsx
  src/components/Settings/FormItem.tsx
  src/routes/index.ts
Labels: size/S

#262 Fix: example flows
  .gitignore
  cypress.json
  cypress/integration/views/flowview.ts
  cypress/integration/visual-tests/flowDesign.ts
  package-lock.json
  package.json
  src/components/FlowChart/ChartNode.tsx
  src/components/FlowChart/FlowChart.tsx
  src/components/FlowChart/FlowSelection.tsx
  src/helpers/flow-chart.ts
  src/index.tsx
  src/modals/PodEdit.tsx
  src/redux/flows/flows.reducer.ts
Labels: size/XL

#272 docs: create deployment documentation
  .github/workflows/deploy-hub.yml
  .github/workflows/deploy.yml
  README.md
  deployment.md
Labels: size/S

#276 Fix: multiple pods bug
  src/components/FlowChart/FlowChart.tsx
  src/components/FlowChart/SidebarItem.tsx
Labels: size/XS

#270 Fix-269
  src/helpers/tests/utils.test.ts
  src/helpers/utils.ts
  src/index.tsx
Labels: size/S

#264 Bug/246 filter selection disappearing
  cypress/integration/views/hubView.ts
  src/components/Hub/HubImagesList.tsx
Labels: size/S

#279 feat: add exempts for the stale action
  .github/workflows/stale.yml
Labels: size/XS

#278 fix(hub): don't display images when no images match the query
  src/components/Hub/HubImagesList.tsx
  src/redux/hub/hub.reducer.ts
  src/redux/hub/hub.selectors.ts
  src/redux/hub/hub.test.ts
Labels: size/S
