Repository jina-ai/dashboard, pull requests merged in 2021-04, with the labels that each got.

#285 test: add tes cases to withTracker component
  src/withTracker.test.tsx
  src/withTracker.tsx
Labels: size/S

#277 test: add integration tests for logstream logs
  cypress.json
  cypress/integration/views/flowview.ts
  cypress/integration/views/logsView.ts
  src/components/LogStream/LogsTable.tsx
Labels: size/S

#258 Added encoding to the url , url will be encoded a per the package sel…
  src/components/Hub/ImageCard.test.tsx
  src/components/Hub/ImageCard.tsx
  src/components/Hub/__snapshots__/ImageCard.test.tsx.snap
  src/routes/Dashboard.tsx
Labels: size/S

#261 Test cases
  cypress/integration/views/homeview.ts
  cypress/integration/views/hubView.ts
  src/apps/Dashboard.tsx
  src/components/Common/InfoBanner.test.tsx
  src/components/Common/InfoToast.test.tsx
  src/components/Common/PageTitle.test.tsx
  src/components/Hub/ImageCard.tsx
  src/components/Hub/__snapshots__/ImageCard.test.tsx.snap
  src/services/tests/hubApi.test.ts
  src/setupTests.js
Labels: size/M

#290 add feature switch for HomeView
  .env
  .env.production
  deployment.md
  package-lock.json
  package.json
  src/helpers/featureSwitch.ts
  src/helpers/tests/featureSwitch.test.ts
  src/routes/Dashboard.tsx
  src/views/HomeView.tsx
Labels: size/M

#289 fix(flow-design): fix save button at flow design page's issue (#288)
  .gitignore
  cypress/integration/views/flowview.ts
  src/components/FlowChart/CommandBar.tsx
  src/views/FlowView.tsx
Labels: size/S

#293 chore: disable sentry in local and testing environments
  src/index.tsx
Labels: size/S

#292 Feat/material UI
  cypress/integration/views/homeview.ts
  package-lock.json
  package.json
  src/components/Common/SpinningLoader.tsx
  src/components/Hub/HubOverviewAction.tsx
  src/components/Hub/__snapshots__/HubOverviewActionsContainer.test.tsx.snap
  src/components/LogStream/LogItem.tsx
  src/components/LogStream/LogsTableHeader.tsx
  src/components/Styleguide/ColorsPage.tsx
  src/components/Styleguide/MiscPage.tsx
  src/components/Styleguide/TypographyPage.tsx
  src/index.tsx
Labels: size/L

#263 feat: workspace redux initial
  .env
  .env.production
  cypress/integration/views/flowview.ts
  cypress/integration/views/homeview.ts
  cypress/integration/views/logsView.ts
  cypress/integration/visual-tests/flowDesign.ts
  package-lock.json
  package.json
  src/App.css
  src/apps/Dashboard.tsx
  src/components/Common/MultiFilterSelect.tsx
  src/components/Common/SpinningLoader.tsx
  src/components/FlowChart/CommandBar.tsx
  src/components/FlowChart/FlowChart.tsx
  src/components/FlowChart/FlowSelection.tsx
  src/components/FlowChart/Sidebar.tsx
  src/components/FlowChart/WorkspaceSelection.tsx
  src/components/Hub/HubOverviewAction.tsx
  src/components/Hub/ImageCard.test.tsx
  src/components/LogStream/LogsTable.tsx
  src/components/LogStream/LogsTableHeader.tsx
  src/components/Settings/FormItem.tsx
  src/components/Settings/Settings.tsx
  src/components/Settings/options.ts
  src/components/Styleguide/ColorsPage.tsx
  src/components/Styleguide/MiscPage.tsx
  src/components/Styleguide/TypographyPage.tsx
  src/data/exampleData.ts
  src/data/exampleFlows.ts
  src/helpers/featureSwitch.ts
  src/helpers/flow-chart.ts
  src/helpers/tests/featureSwitch.test.ts
  src/helpers/tests/flow-chart.testData.ts
  src/index.tsx
  src/layouts/IconSidebar.tsx
  src/modals/PodEdit.tsx
  src/modals/QuerySearchModal.tsx
  src/redux/flows/flows.actions.ts
  src/redux/flows/flows.constants.ts
  src/redux/flows/flows.reducer.ts
  src/redux/flows/flows.selectors.ts
  src/redux/flows/flows.test.ts
  src/redux/flows/flows.testData.ts
  src/redux/flows/flows.types.ts
  src/redux/global/global.actions.ts
  src/redux/global/global.test.ts
  src/redux/global/global.types.ts
  src/redux/index.ts
  src/redux/settings/settings.constants.ts
  src/redux/settings/settings.types.ts
  src/routes/Dashboard.tsx
  src/services/gatewayClient.ts
  src/services/jinad.ts
  src/services/tests/gatewayClient.test.ts
  src/services/tests/gatewayClient.testData.ts
  src/services/tests/jinad.test.ts
  src/services/tests/jinad.testData.ts
  src/views/FlowView.tsx
  src/views/HomeView.tsx
  src/withTracker.test.tsx
Labels: size/XL

#304 Fix 302
  cypress/integration/views/flowview.ts
  src/redux/flows/flows.reducer.ts
Labels: size/S

#284 feat: stack banners
  cypress/integration/visual-tests/flowDesign.ts
  src/components/Common/InfoToast.tsx
  src/layouts/HubLayout.tsx
  src/layouts/IconSidebar.tsx
  src/redux/global/global.constants.ts
  src/redux/global/global.reducer.ts
  src/redux/global/global.selectors.ts
  src/redux/global/global.test.ts
  src/redux/global/global.types.ts
Labels: size/M

#308 Feat: Multi modal example
  src/components/FlowChart/WorkspaceSelection.tsx
  src/data/multiModalExample.ts
  src/services/config.ts
  src/services/multiModalScript.ts
Labels: size/L

#256 Feat GitHub oauth 219
  .env
  cypress/integration/global/login.ts
  cypress/integration/views/flowview.ts
  cypress/plugins/index.js
  package-lock.json
  package.json
  src/apps/Dashboard.tsx
  src/components/Layout/MainNavbar/ConnectionIndicator.tsx
  src/components/Layout/MainNavbar/MainNavbar.tsx
  src/components/Layout/MainNavbar/UserActions.tsx
  src/redux/flows/flows.test.ts
  src/redux/global/global.actions.ts
  src/redux/global/global.constants.ts
  src/redux/global/global.reducer.ts
  src/redux/global/global.selectors.ts
  src/redux/global/global.test.ts
  src/redux/global/global.types.ts
  src/routes/Dashboard.tsx
  src/services/github.ts
  src/services/tests/github.test.ts
  src/views/LogIn.tsx
Labels: size/L

#280 feat(pod): change pod boolean props UI to switch button (issue #243)
  cypress/integration/views/podView.ts
  dev-resources/sample-data/args-flow.json
  dev-resources/sample-data/args-pea.json
  dev-resources/sample-data/args-pod.json
  src/modals/PodEdit.tsx
Labels: size/S
