Repository jina-ai/dashboard, pull requests merged in 2021-05, with the labels that each got.

#313 Feat: Send gateway port to multi-modal frontend
  src/services/multiModalScript.ts
Labels: size/XS

#315 Fix/300 filter interface cleanup
  cypress/integration/views/hubView.ts
  package-lock.json
  package.json
  src/components/Hub/FilterButton.tsx
  src/components/Hub/HubFilters.test.tsx
  src/components/Hub/HubFilters.tsx
  src/components/Hub/HubImageLIst.test.tsx
  src/components/Hub/HubImagesList.tsx
  src/redux/hub/hub.actions.ts
  src/redux/hub/hub.constants.ts
  src/redux/hub/hub.reducer.ts
  src/redux/hub/hub.selectors.ts
  src/redux/hub/hub.test.ts
  src/redux/hub/hub.types.ts
  src/services/hubApi.ts
Labels: size/L

#319 Feat/299 hub details restyle
  src/components/Common/Typography.tsx
  src/components/Hub/CodeSnippetWithCopy.tsx
  src/components/Hub/CopyCommand.tsx
  src/components/Hub/ImageCard.tsx
  src/components/Hub/ImageDetails.tsx
  src/components/Hub/Readme.tsx
  src/components/Hub/__snapshots__/ImageCard.test.tsx.snap
  src/components/Hub/__snapshots__/ImageDetails.test.tsx.snap
  src/components/Hub/__snapshots__/Readme.test.tsx.snap
  src/components/Styleguide/__snapshots__/ColorsPage.test.tsx.snap
  src/components/Styleguide/__snapshots__/TypographyPage.test.tsx.snap
  src/emotion.d.ts
  src/helpers/tests/utils.test.ts
  src/theme.ts
  src/views/PackageView.tsx
Labels: size/L

#322 docs(readme): rm missing eah god image link
  README.md
Labels: size/XS

#325 Add items for replicating visual designs
  .github/pull_request_template.md
Labels: size/XS

#324 Feat: hub-nav-bar
  src/components/Hub/HubNavigationBar.tsx
  src/components/Styleguide/__snapshots__/ColorsPage.test.tsx.snap
  src/emotion.d.ts
  src/index.tsx
  src/theme.ts
  src/views/HubView.tsx
Labels: size/M

#327 Fixes: Theming Object collision#326
  src/components/Common/NavigateButton.tsx
  src/components/Common/SpinningLoader.tsx
  src/components/Common/Typography.tsx
  src/components/FlowChart/CommandBar.tsx
  src/components/Hub/CodeSnippetWithCopy.tsx
  src/components/Hub/HubFilters.tsx
  src/components/Hub/HubNavigationBar.tsx
  src/components/Hub/ImageCard.tsx
  src/components/Hub/ImageDetails.tsx
  src/components/Hub/Readme.tsx
  src/components/Hub/__snapshots__/HubOverviewActionsContainer.test.tsx.snap
  src/components/Hub/__snapshots__/ImageCard.test.tsx.snap
  src/components/Hub/__snapshots__/ImageDetails.test.tsx.snap
  src/components/Hub/__snapshots__/Readme.test.tsx.snap
  src/components/Styleguide/ColorsPage.tsx
  src/components/Styleguide/__snapshots__/ColorsPage.test.tsx.snap
  src/components/Styleguide/__snapshots__/MiscPage.test.tsx.snap
  src/emotion.d.ts
  src/index.tsx
  src/theme.ts
Labels: size/XL

#328 fix: palette bugs
  src/components/FlowChart/ChartNode.tsx
  src/components/Hub/HubOverviewAction.tsx
  src/components/Hub/__snapshots__/HubOverviewActionsContainer.test.tsx.snap
  src/components/LogStream/levels.ts
Labels: size/S

#332 feat: increasee the days before stale
  .github/workflows/stale.yml
Labels: size/XS
