Repository jina-ai/dashboard, pull requests merged in 2021-07, with the labels that each got.

#347 ci: push swagger build
  .github/workflows/deploy-swaggerui.yml
Labels: size/S

#350 fix: update deploy command
  .github/workflows/deploy-swaggerui.yml
Labels: size/XS

#348 Feat swagger
  .github/workflows/deploy-hub.yml
  .github/workflows/deploy.yml
  CONTRIBUTING.md
  README.md
  package-lock.json
  package.json
  src/apps/Dashboard.tsx
  src/apps/Hub.tsx
  src/apps/Styleguide.tsx
  src/apps/Swagger.tsx
  src/apps/utils.ts
  src/components/Common/ExpandingSearchbar.tsx
  src/components/DebuggingTool/CustomLiveResponse.tsx
  src/components/DebuggingTool/CustomRequestBodyEditor.tsx
  src/components/DebuggingTool/DocumentTabs.tsx
  src/components/DebuggingTool/FlowChartNodes.tsx
  src/components/DebuggingTool/Matches.tsx
  src/components/DebuggingTool/Request.tsx
  src/components/DebuggingTool/Response.tsx
  src/components/DebuggingTool/Scores.tsx
  src/components/DebuggingTool/tests/Matches.test.tsx
  src/components/DebuggingTool/tests/Matches.testData.ts
  src/components/Hub/CodeSnippetWithCopy.tsx
  src/components/Hub/HubFilters.tsx
  src/components/Hub/HubImagesListPreview.tsx
  src/components/Hub/HubNavigationBar.tsx
  src/components/Hub/HubOverviewActionsContainer.tsx
  src/components/Hub/HubRecommendedCategories.tsx
  src/components/Hub/ImageCard.tsx
  src/components/Hub/ImageDetails.tsx
  src/components/Layout/MainNavbar/MainNavbar.tsx
  src/components/Layout/MainNavbar/UserActions.tsx
  src/components/LogStream/LogsTable.tsx
  src/createPalette.d.ts
  src/helpers/format.ts
  src/helpers/tests/format.test.ts
  src/helpers/tests/utils.test.ts
  src/helpers/utils.ts
  src/index.tsx
  src/layouts/HubLayout.tsx
  src/layouts/IconSidebar.tsx
  src/layouts/SwaggerLayout.tsx
  src/layouts/index.ts
  src/redux/flows/flows.reducer.ts
  src/redux/flows/flows.selectors.ts
  src/redux/flows/flows.test.ts
  src/redux/hub/hub.reducer.ts
  src/routes/Dashboard.tsx
  src/routes/Hub.tsx
  src/routes/Swagger.tsx
  src/views/DebuggingTool.tsx
  src/views/PackageView.tsx
  src/views/SwaggerView.tsx
  tsconfig.json
Labels: size/XL

#355 fix: rm default to video
  src/components/DebuggingTool/FlowChartNodes.tsx
Labels: size/XS
